site_name: 常州大学开源软件协会
site_description: 常州大学学生非社团自由组织 - 欢迎加群 947560153
site_url: http://cczu-ossa.github.io/home
site_author: CCZU-OSSA
repo_name: CCZU-OSSA/home
repo_url: https://github.com/CCZU-OSSA/home
copyright: Copyright &copy; 2023 常州大学开源软件协会
edit_uri: edit/main/docs/

nav:
  - 主页: index.md
  - 索引:
      - indexs/for-fresher.md
      - indexs/cczu-links.md
      - indexs/projects.md
  - 博客:
      - blog/index.md
      - 软件相关:
          - blog/software/edge-plugins-optimize.md
      - 硬件相关:
          - blog/hardware/index.md
      - 算法相关:
          - blog/algorithm/guide-to-algorithm-competitions.md
  - PDF:
      - pdf/index.md
      - CMCC校园网路由配置: pdf/cczu-cmcc-router.pdf
  - 留言板:
      - chat/index.md
theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  language: zh
  plugins:
    - blog:
        post_url_date_format: yyyy/MM/dd
        post_date_format: full
        blog_dir: 博客
        categories_allowed:
          - Search
          - Performance

    - social:
        cards_layout: default
        cards_layout_options:
          font_family: Noto Sans SC
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - toc.follow
    - navigation.path
    - navigation.top
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: glow
      toggle:
        icon: material/brightness-7
        name: 切换暗色

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: glow-dark
      toggle:
        icon: material/brightness-4
        name: 切换亮色

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CCZU-OSSA
    - icon: fontawesome/brands/qq
      link: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=6wgGLJ_NmKQl7f9Ws6JAprbTwmG9Ouei&authKey=g7bXX%2Bn2dHlbecf%2B8QfGJ15IFVOmEdGTJuoLYfviLg7TZIsZCu45sngzZfL3KktN&noverify=0&group_code=947560153
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zqhURaJ8

extra_css:
  - assets/fonts/ResourceHanRoundedCN-Medium/font.css
  - assets/fonts/MapleMono-SC-NF-Bold/font.css
  - assets/stylesheets/fonts.css
  - assets/stylesheets/colorscheme.css
markdown_extensions:
  - admonition
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: "¶"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

plugins:
  - search
  - offline
  - git-revision-date-localized:
      locale: zh
      fallback_to_build_date: true
  - git-committers:
      repository: CCZU-OSSA/home
      branch: main